// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_RPC_IA20_NET_CONN_ENGINE_FB_H_
#define FLATBUFFERS_GENERATED_RPC_IA20_NET_CONN_ENGINE_FB_H_

#include "flatbuffers/flatbuffers.h"

namespace IA20 {
namespace Net {
namespace Conn {
namespace Engine {
namespace FB {

struct Header;

struct LogEntryId;

struct VoteRequest;
struct VoteRequestBuilder;
struct VoteRequestT;

struct VoteResponse;
struct VoteResponseBuilder;
struct VoteResponseT;

struct AppendLogRequest;
struct AppendLogRequestBuilder;
struct AppendLogRequestT;

struct AppendLogResponse;
struct AppendLogResponseBuilder;
struct AppendLogResponseT;

struct Message;
struct MessageBuilder;
struct MessageT;

inline const flatbuffers::TypeTable *HeaderTypeTable();

inline const flatbuffers::TypeTable *LogEntryIdTypeTable();

inline const flatbuffers::TypeTable *VoteRequestTypeTable();

inline const flatbuffers::TypeTable *VoteResponseTypeTable();

inline const flatbuffers::TypeTable *AppendLogRequestTypeTable();

inline const flatbuffers::TypeTable *AppendLogResponseTypeTable();

inline const flatbuffers::TypeTable *MessageTypeTable();

enum Action {
  Action_NONE = 0,
  Action_VoteRequest = 1,
  Action_VoteResponse = 2,
  Action_AppendLogRequest = 3,
  Action_AppendLogResponse = 4,
  Action_MIN = Action_NONE,
  Action_MAX = Action_AppendLogResponse
};

inline const Action (&EnumValuesAction())[5] {
  static const Action values[] = {
    Action_NONE,
    Action_VoteRequest,
    Action_VoteResponse,
    Action_AppendLogRequest,
    Action_AppendLogResponse
  };
  return values;
}

inline const char * const *EnumNamesAction() {
  static const char * const names[6] = {
    "NONE",
    "VoteRequest",
    "VoteResponse",
    "AppendLogRequest",
    "AppendLogResponse",
    nullptr
  };
  return names;
}

inline const char *EnumNameAction(Action e) {
  if (flatbuffers::IsOutRange(e, Action_NONE, Action_AppendLogResponse)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAction()[index];
}

template<typename T> struct ActionTraits {
  static const Action enum_value = Action_NONE;
};

template<> struct ActionTraits<IA20::Net::Conn::Engine::FB::VoteRequest> {
  static const Action enum_value = Action_VoteRequest;
};

template<> struct ActionTraits<IA20::Net::Conn::Engine::FB::VoteResponse> {
  static const Action enum_value = Action_VoteResponse;
};

template<> struct ActionTraits<IA20::Net::Conn::Engine::FB::AppendLogRequest> {
  static const Action enum_value = Action_AppendLogRequest;
};

template<> struct ActionTraits<IA20::Net::Conn::Engine::FB::AppendLogResponse> {
  static const Action enum_value = Action_AppendLogResponse;
};

struct ActionUnion {
  Action type;
  void *value;

  ActionUnion() : type(Action_NONE), value(nullptr) {}
  ActionUnion(ActionUnion&& u) FLATBUFFERS_NOEXCEPT :
    type(Action_NONE), value(nullptr)
    { std::swap(type, u.type); std::swap(value, u.value); }
  ActionUnion(const ActionUnion &);
  ActionUnion &operator=(const ActionUnion &u)
    { ActionUnion t(u); std::swap(type, t.type); std::swap(value, t.value); return *this; }
  ActionUnion &operator=(ActionUnion &&u) FLATBUFFERS_NOEXCEPT
    { std::swap(type, u.type); std::swap(value, u.value); return *this; }
  ~ActionUnion() { Reset(); }

  void Reset();

#ifndef FLATBUFFERS_CPP98_STL
  template <typename T>
  void Set(T&& val) {
    using RT = typename std::remove_reference<T>::type;
    Reset();
    type = ActionTraits<typename RT::TableType>::enum_value;
    if (type != Action_NONE) {
      value = new RT(std::forward<T>(val));
    }
  }
#endif  // FLATBUFFERS_CPP98_STL

  static void *UnPack(const void *obj, Action type, const flatbuffers::resolver_function_t *resolver);
  flatbuffers::Offset<void> Pack(flatbuffers::FlatBufferBuilder &_fbb, const flatbuffers::rehasher_function_t *_rehasher = nullptr) const;

  IA20::Net::Conn::Engine::FB::VoteRequestT *AsVoteRequest() {
    return type == Action_VoteRequest ?
      reinterpret_cast<IA20::Net::Conn::Engine::FB::VoteRequestT *>(value) : nullptr;
  }
  const IA20::Net::Conn::Engine::FB::VoteRequestT *AsVoteRequest() const {
    return type == Action_VoteRequest ?
      reinterpret_cast<const IA20::Net::Conn::Engine::FB::VoteRequestT *>(value) : nullptr;
  }
  IA20::Net::Conn::Engine::FB::VoteResponseT *AsVoteResponse() {
    return type == Action_VoteResponse ?
      reinterpret_cast<IA20::Net::Conn::Engine::FB::VoteResponseT *>(value) : nullptr;
  }
  const IA20::Net::Conn::Engine::FB::VoteResponseT *AsVoteResponse() const {
    return type == Action_VoteResponse ?
      reinterpret_cast<const IA20::Net::Conn::Engine::FB::VoteResponseT *>(value) : nullptr;
  }
  IA20::Net::Conn::Engine::FB::AppendLogRequestT *AsAppendLogRequest() {
    return type == Action_AppendLogRequest ?
      reinterpret_cast<IA20::Net::Conn::Engine::FB::AppendLogRequestT *>(value) : nullptr;
  }
  const IA20::Net::Conn::Engine::FB::AppendLogRequestT *AsAppendLogRequest() const {
    return type == Action_AppendLogRequest ?
      reinterpret_cast<const IA20::Net::Conn::Engine::FB::AppendLogRequestT *>(value) : nullptr;
  }
  IA20::Net::Conn::Engine::FB::AppendLogResponseT *AsAppendLogResponse() {
    return type == Action_AppendLogResponse ?
      reinterpret_cast<IA20::Net::Conn::Engine::FB::AppendLogResponseT *>(value) : nullptr;
  }
  const IA20::Net::Conn::Engine::FB::AppendLogResponseT *AsAppendLogResponse() const {
    return type == Action_AppendLogResponse ?
      reinterpret_cast<const IA20::Net::Conn::Engine::FB::AppendLogResponseT *>(value) : nullptr;
  }
};

bool VerifyAction(flatbuffers::Verifier &verifier, const void *obj, Action type);
bool VerifyActionVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(2) Header FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t dstServerId_;
  uint16_t srcServerId_;

 public:
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return HeaderTypeTable();
  }
  Header() {
    memset(static_cast<void *>(this), 0, sizeof(Header));
  }
  Header(uint16_t _dstServerId, uint16_t _srcServerId)
      : dstServerId_(flatbuffers::EndianScalar(_dstServerId)),
        srcServerId_(flatbuffers::EndianScalar(_srcServerId)) {
  }
  uint16_t dstServerId() const {
    return flatbuffers::EndianScalar(dstServerId_);
  }
  void mutate_dstServerId(uint16_t _dstServerId) {
    flatbuffers::WriteScalar(&dstServerId_, _dstServerId);
  }
  uint16_t srcServerId() const {
    return flatbuffers::EndianScalar(srcServerId_);
  }
  void mutate_srcServerId(uint16_t _srcServerId) {
    flatbuffers::WriteScalar(&srcServerId_, _srcServerId);
  }
};
FLATBUFFERS_STRUCT_END(Header, 4);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) LogEntryId FLATBUFFERS_FINAL_CLASS {
 private:
  uint16_t term_;
  int16_t padding0__;
  uint32_t index_;

 public:
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return LogEntryIdTypeTable();
  }
  LogEntryId() {
    memset(static_cast<void *>(this), 0, sizeof(LogEntryId));
  }
  LogEntryId(uint16_t _term, uint32_t _index)
      : term_(flatbuffers::EndianScalar(_term)),
        padding0__(0),
        index_(flatbuffers::EndianScalar(_index)) {
    (void)padding0__;
  }
  uint16_t term() const {
    return flatbuffers::EndianScalar(term_);
  }
  void mutate_term(uint16_t _term) {
    flatbuffers::WriteScalar(&term_, _term);
  }
  uint32_t index() const {
    return flatbuffers::EndianScalar(index_);
  }
  void mutate_index(uint32_t _index) {
    flatbuffers::WriteScalar(&index_, _index);
  }
};
FLATBUFFERS_STRUCT_END(LogEntryId, 8);

struct VoteRequestT : public flatbuffers::NativeTable {
  typedef VoteRequest TableType;
  uint16_t term;
  uint16_t candidate;
  std::unique_ptr<IA20::Net::Conn::Engine::FB::LogEntryId> lastLogEntry;
  VoteRequestT()
      : term(0),
        candidate(0) {
  }
};

struct VoteRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef VoteRequestT NativeTableType;
  typedef VoteRequestBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return VoteRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TERM = 4,
    VT_CANDIDATE = 6,
    VT_LASTLOGENTRY = 8
  };
  uint16_t term() const {
    return GetField<uint16_t>(VT_TERM, 0);
  }
  bool mutate_term(uint16_t _term) {
    return SetField<uint16_t>(VT_TERM, _term, 0);
  }
  uint16_t candidate() const {
    return GetField<uint16_t>(VT_CANDIDATE, 0);
  }
  bool mutate_candidate(uint16_t _candidate) {
    return SetField<uint16_t>(VT_CANDIDATE, _candidate, 0);
  }
  const IA20::Net::Conn::Engine::FB::LogEntryId *lastLogEntry() const {
    return GetStruct<const IA20::Net::Conn::Engine::FB::LogEntryId *>(VT_LASTLOGENTRY);
  }
  IA20::Net::Conn::Engine::FB::LogEntryId *mutable_lastLogEntry() {
    return GetStruct<IA20::Net::Conn::Engine::FB::LogEntryId *>(VT_LASTLOGENTRY);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TERM) &&
           VerifyField<uint16_t>(verifier, VT_CANDIDATE) &&
           VerifyField<IA20::Net::Conn::Engine::FB::LogEntryId>(verifier, VT_LASTLOGENTRY) &&
           verifier.EndTable();
  }
  VoteRequestT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(VoteRequestT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<VoteRequest> Pack(flatbuffers::FlatBufferBuilder &_fbb, const VoteRequestT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct VoteRequestBuilder {
  typedef VoteRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_term(uint16_t term) {
    fbb_.AddElement<uint16_t>(VoteRequest::VT_TERM, term, 0);
  }
  void add_candidate(uint16_t candidate) {
    fbb_.AddElement<uint16_t>(VoteRequest::VT_CANDIDATE, candidate, 0);
  }
  void add_lastLogEntry(const IA20::Net::Conn::Engine::FB::LogEntryId *lastLogEntry) {
    fbb_.AddStruct(VoteRequest::VT_LASTLOGENTRY, lastLogEntry);
  }
  explicit VoteRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  VoteRequestBuilder &operator=(const VoteRequestBuilder &);
  flatbuffers::Offset<VoteRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<VoteRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<VoteRequest> CreateVoteRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t term = 0,
    uint16_t candidate = 0,
    const IA20::Net::Conn::Engine::FB::LogEntryId *lastLogEntry = 0) {
  VoteRequestBuilder builder_(_fbb);
  builder_.add_lastLogEntry(lastLogEntry);
  builder_.add_candidate(candidate);
  builder_.add_term(term);
  return builder_.Finish();
}

flatbuffers::Offset<VoteRequest> CreateVoteRequest(flatbuffers::FlatBufferBuilder &_fbb, const VoteRequestT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct VoteResponseT : public flatbuffers::NativeTable {
  typedef VoteResponse TableType;
  uint16_t term;
  uint16_t candidate;
  bool granted;
  VoteResponseT()
      : term(0),
        candidate(0),
        granted(false) {
  }
};

struct VoteResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef VoteResponseT NativeTableType;
  typedef VoteResponseBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return VoteResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TERM = 4,
    VT_CANDIDATE = 6,
    VT_GRANTED = 8
  };
  uint16_t term() const {
    return GetField<uint16_t>(VT_TERM, 0);
  }
  bool mutate_term(uint16_t _term) {
    return SetField<uint16_t>(VT_TERM, _term, 0);
  }
  uint16_t candidate() const {
    return GetField<uint16_t>(VT_CANDIDATE, 0);
  }
  bool mutate_candidate(uint16_t _candidate) {
    return SetField<uint16_t>(VT_CANDIDATE, _candidate, 0);
  }
  bool granted() const {
    return GetField<uint8_t>(VT_GRANTED, 0) != 0;
  }
  bool mutate_granted(bool _granted) {
    return SetField<uint8_t>(VT_GRANTED, static_cast<uint8_t>(_granted), 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_TERM) &&
           VerifyField<uint16_t>(verifier, VT_CANDIDATE) &&
           VerifyField<uint8_t>(verifier, VT_GRANTED) &&
           verifier.EndTable();
  }
  VoteResponseT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(VoteResponseT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<VoteResponse> Pack(flatbuffers::FlatBufferBuilder &_fbb, const VoteResponseT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct VoteResponseBuilder {
  typedef VoteResponse Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_term(uint16_t term) {
    fbb_.AddElement<uint16_t>(VoteResponse::VT_TERM, term, 0);
  }
  void add_candidate(uint16_t candidate) {
    fbb_.AddElement<uint16_t>(VoteResponse::VT_CANDIDATE, candidate, 0);
  }
  void add_granted(bool granted) {
    fbb_.AddElement<uint8_t>(VoteResponse::VT_GRANTED, static_cast<uint8_t>(granted), 0);
  }
  explicit VoteResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  VoteResponseBuilder &operator=(const VoteResponseBuilder &);
  flatbuffers::Offset<VoteResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<VoteResponse>(end);
    return o;
  }
};

inline flatbuffers::Offset<VoteResponse> CreateVoteResponse(
    flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t term = 0,
    uint16_t candidate = 0,
    bool granted = false) {
  VoteResponseBuilder builder_(_fbb);
  builder_.add_candidate(candidate);
  builder_.add_term(term);
  builder_.add_granted(granted);
  return builder_.Finish();
}

flatbuffers::Offset<VoteResponse> CreateVoteResponse(flatbuffers::FlatBufferBuilder &_fbb, const VoteResponseT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct AppendLogRequestT : public flatbuffers::NativeTable {
  typedef AppendLogRequest TableType;
  std::unique_ptr<IA20::Net::Conn::Engine::FB::LogEntryId> matchLogEntry;
  std::unique_ptr<IA20::Net::Conn::Engine::FB::LogEntryId> dataLogEntry;
  uint32_t leaderCommitIndex;
  std::vector<uint8_t> data;
  AppendLogRequestT()
      : leaderCommitIndex(0) {
  }
};

struct AppendLogRequest FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AppendLogRequestT NativeTableType;
  typedef AppendLogRequestBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return AppendLogRequestTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MATCHLOGENTRY = 4,
    VT_DATALOGENTRY = 6,
    VT_LEADERCOMMITINDEX = 8,
    VT_DATA = 10
  };
  const IA20::Net::Conn::Engine::FB::LogEntryId *matchLogEntry() const {
    return GetStruct<const IA20::Net::Conn::Engine::FB::LogEntryId *>(VT_MATCHLOGENTRY);
  }
  IA20::Net::Conn::Engine::FB::LogEntryId *mutable_matchLogEntry() {
    return GetStruct<IA20::Net::Conn::Engine::FB::LogEntryId *>(VT_MATCHLOGENTRY);
  }
  const IA20::Net::Conn::Engine::FB::LogEntryId *dataLogEntry() const {
    return GetStruct<const IA20::Net::Conn::Engine::FB::LogEntryId *>(VT_DATALOGENTRY);
  }
  IA20::Net::Conn::Engine::FB::LogEntryId *mutable_dataLogEntry() {
    return GetStruct<IA20::Net::Conn::Engine::FB::LogEntryId *>(VT_DATALOGENTRY);
  }
  uint32_t leaderCommitIndex() const {
    return GetField<uint32_t>(VT_LEADERCOMMITINDEX, 0);
  }
  bool mutate_leaderCommitIndex(uint32_t _leaderCommitIndex) {
    return SetField<uint32_t>(VT_LEADERCOMMITINDEX, _leaderCommitIndex, 0);
  }
  const flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  flatbuffers::Vector<uint8_t> *mutable_data() {
    return GetPointer<flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<IA20::Net::Conn::Engine::FB::LogEntryId>(verifier, VT_MATCHLOGENTRY) &&
           VerifyField<IA20::Net::Conn::Engine::FB::LogEntryId>(verifier, VT_DATALOGENTRY) &&
           VerifyField<uint32_t>(verifier, VT_LEADERCOMMITINDEX) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
  AppendLogRequestT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AppendLogRequestT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<AppendLogRequest> Pack(flatbuffers::FlatBufferBuilder &_fbb, const AppendLogRequestT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AppendLogRequestBuilder {
  typedef AppendLogRequest Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_matchLogEntry(const IA20::Net::Conn::Engine::FB::LogEntryId *matchLogEntry) {
    fbb_.AddStruct(AppendLogRequest::VT_MATCHLOGENTRY, matchLogEntry);
  }
  void add_dataLogEntry(const IA20::Net::Conn::Engine::FB::LogEntryId *dataLogEntry) {
    fbb_.AddStruct(AppendLogRequest::VT_DATALOGENTRY, dataLogEntry);
  }
  void add_leaderCommitIndex(uint32_t leaderCommitIndex) {
    fbb_.AddElement<uint32_t>(AppendLogRequest::VT_LEADERCOMMITINDEX, leaderCommitIndex, 0);
  }
  void add_data(flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(AppendLogRequest::VT_DATA, data);
  }
  explicit AppendLogRequestBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  AppendLogRequestBuilder &operator=(const AppendLogRequestBuilder &);
  flatbuffers::Offset<AppendLogRequest> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AppendLogRequest>(end);
    return o;
  }
};

inline flatbuffers::Offset<AppendLogRequest> CreateAppendLogRequest(
    flatbuffers::FlatBufferBuilder &_fbb,
    const IA20::Net::Conn::Engine::FB::LogEntryId *matchLogEntry = 0,
    const IA20::Net::Conn::Engine::FB::LogEntryId *dataLogEntry = 0,
    uint32_t leaderCommitIndex = 0,
    flatbuffers::Offset<flatbuffers::Vector<uint8_t>> data = 0) {
  AppendLogRequestBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_leaderCommitIndex(leaderCommitIndex);
  builder_.add_dataLogEntry(dataLogEntry);
  builder_.add_matchLogEntry(matchLogEntry);
  return builder_.Finish();
}

inline flatbuffers::Offset<AppendLogRequest> CreateAppendLogRequestDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const IA20::Net::Conn::Engine::FB::LogEntryId *matchLogEntry = 0,
    const IA20::Net::Conn::Engine::FB::LogEntryId *dataLogEntry = 0,
    uint32_t leaderCommitIndex = 0,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return IA20::Net::Conn::Engine::FB::CreateAppendLogRequest(
      _fbb,
      matchLogEntry,
      dataLogEntry,
      leaderCommitIndex,
      data__);
}

flatbuffers::Offset<AppendLogRequest> CreateAppendLogRequest(flatbuffers::FlatBufferBuilder &_fbb, const AppendLogRequestT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct AppendLogResponseT : public flatbuffers::NativeTable {
  typedef AppendLogResponse TableType;
  std::unique_ptr<IA20::Net::Conn::Engine::FB::LogEntryId> dataLogEntry;
  bool success;
  AppendLogResponseT()
      : success(false) {
  }
};

struct AppendLogResponse FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef AppendLogResponseT NativeTableType;
  typedef AppendLogResponseBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return AppendLogResponseTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_DATALOGENTRY = 4,
    VT_SUCCESS = 6
  };
  const IA20::Net::Conn::Engine::FB::LogEntryId *dataLogEntry() const {
    return GetStruct<const IA20::Net::Conn::Engine::FB::LogEntryId *>(VT_DATALOGENTRY);
  }
  IA20::Net::Conn::Engine::FB::LogEntryId *mutable_dataLogEntry() {
    return GetStruct<IA20::Net::Conn::Engine::FB::LogEntryId *>(VT_DATALOGENTRY);
  }
  bool success() const {
    return GetField<uint8_t>(VT_SUCCESS, 0) != 0;
  }
  bool mutate_success(bool _success) {
    return SetField<uint8_t>(VT_SUCCESS, static_cast<uint8_t>(_success), 0);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<IA20::Net::Conn::Engine::FB::LogEntryId>(verifier, VT_DATALOGENTRY) &&
           VerifyField<uint8_t>(verifier, VT_SUCCESS) &&
           verifier.EndTable();
  }
  AppendLogResponseT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(AppendLogResponseT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<AppendLogResponse> Pack(flatbuffers::FlatBufferBuilder &_fbb, const AppendLogResponseT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

struct AppendLogResponseBuilder {
  typedef AppendLogResponse Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_dataLogEntry(const IA20::Net::Conn::Engine::FB::LogEntryId *dataLogEntry) {
    fbb_.AddStruct(AppendLogResponse::VT_DATALOGENTRY, dataLogEntry);
  }
  void add_success(bool success) {
    fbb_.AddElement<uint8_t>(AppendLogResponse::VT_SUCCESS, static_cast<uint8_t>(success), 0);
  }
  explicit AppendLogResponseBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  AppendLogResponseBuilder &operator=(const AppendLogResponseBuilder &);
  flatbuffers::Offset<AppendLogResponse> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<AppendLogResponse>(end);
    return o;
  }
};

inline flatbuffers::Offset<AppendLogResponse> CreateAppendLogResponse(
    flatbuffers::FlatBufferBuilder &_fbb,
    const IA20::Net::Conn::Engine::FB::LogEntryId *dataLogEntry = 0,
    bool success = false) {
  AppendLogResponseBuilder builder_(_fbb);
  builder_.add_dataLogEntry(dataLogEntry);
  builder_.add_success(success);
  return builder_.Finish();
}

flatbuffers::Offset<AppendLogResponse> CreateAppendLogResponse(flatbuffers::FlatBufferBuilder &_fbb, const AppendLogResponseT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

struct MessageT : public flatbuffers::NativeTable {
  typedef Message TableType;
  std::unique_ptr<IA20::Net::Conn::Engine::FB::Header> header;
  IA20::Net::Conn::Engine::FB::ActionUnion action;
  MessageT() {
  }
};

struct Message FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  typedef MessageT NativeTableType;
  typedef MessageBuilder Builder;
  static const flatbuffers::TypeTable *MiniReflectTypeTable() {
    return MessageTypeTable();
  }
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_HEADER = 4,
    VT_ACTION_TYPE = 6,
    VT_ACTION = 8
  };
  const IA20::Net::Conn::Engine::FB::Header *header() const {
    return GetStruct<const IA20::Net::Conn::Engine::FB::Header *>(VT_HEADER);
  }
  IA20::Net::Conn::Engine::FB::Header *mutable_header() {
    return GetStruct<IA20::Net::Conn::Engine::FB::Header *>(VT_HEADER);
  }
  IA20::Net::Conn::Engine::FB::Action action_type() const {
    return static_cast<IA20::Net::Conn::Engine::FB::Action>(GetField<uint8_t>(VT_ACTION_TYPE, 0));
  }
  const void *action() const {
    return GetPointer<const void *>(VT_ACTION);
  }
  template<typename T> const T *action_as() const;
  const IA20::Net::Conn::Engine::FB::VoteRequest *action_as_VoteRequest() const {
    return action_type() == IA20::Net::Conn::Engine::FB::Action_VoteRequest ? static_cast<const IA20::Net::Conn::Engine::FB::VoteRequest *>(action()) : nullptr;
  }
  const IA20::Net::Conn::Engine::FB::VoteResponse *action_as_VoteResponse() const {
    return action_type() == IA20::Net::Conn::Engine::FB::Action_VoteResponse ? static_cast<const IA20::Net::Conn::Engine::FB::VoteResponse *>(action()) : nullptr;
  }
  const IA20::Net::Conn::Engine::FB::AppendLogRequest *action_as_AppendLogRequest() const {
    return action_type() == IA20::Net::Conn::Engine::FB::Action_AppendLogRequest ? static_cast<const IA20::Net::Conn::Engine::FB::AppendLogRequest *>(action()) : nullptr;
  }
  const IA20::Net::Conn::Engine::FB::AppendLogResponse *action_as_AppendLogResponse() const {
    return action_type() == IA20::Net::Conn::Engine::FB::Action_AppendLogResponse ? static_cast<const IA20::Net::Conn::Engine::FB::AppendLogResponse *>(action()) : nullptr;
  }
  void *mutable_action() {
    return GetPointer<void *>(VT_ACTION);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<IA20::Net::Conn::Engine::FB::Header>(verifier, VT_HEADER) &&
           VerifyField<uint8_t>(verifier, VT_ACTION_TYPE) &&
           VerifyOffset(verifier, VT_ACTION) &&
           VerifyAction(verifier, action(), action_type()) &&
           verifier.EndTable();
  }
  MessageT *UnPack(const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  void UnPackTo(MessageT *_o, const flatbuffers::resolver_function_t *_resolver = nullptr) const;
  static flatbuffers::Offset<Message> Pack(flatbuffers::FlatBufferBuilder &_fbb, const MessageT* _o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);
};

template<> inline const IA20::Net::Conn::Engine::FB::VoteRequest *Message::action_as<IA20::Net::Conn::Engine::FB::VoteRequest>() const {
  return action_as_VoteRequest();
}

template<> inline const IA20::Net::Conn::Engine::FB::VoteResponse *Message::action_as<IA20::Net::Conn::Engine::FB::VoteResponse>() const {
  return action_as_VoteResponse();
}

template<> inline const IA20::Net::Conn::Engine::FB::AppendLogRequest *Message::action_as<IA20::Net::Conn::Engine::FB::AppendLogRequest>() const {
  return action_as_AppendLogRequest();
}

template<> inline const IA20::Net::Conn::Engine::FB::AppendLogResponse *Message::action_as<IA20::Net::Conn::Engine::FB::AppendLogResponse>() const {
  return action_as_AppendLogResponse();
}

struct MessageBuilder {
  typedef Message Table;
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_header(const IA20::Net::Conn::Engine::FB::Header *header) {
    fbb_.AddStruct(Message::VT_HEADER, header);
  }
  void add_action_type(IA20::Net::Conn::Engine::FB::Action action_type) {
    fbb_.AddElement<uint8_t>(Message::VT_ACTION_TYPE, static_cast<uint8_t>(action_type), 0);
  }
  void add_action(flatbuffers::Offset<void> action) {
    fbb_.AddOffset(Message::VT_ACTION, action);
  }
  explicit MessageBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  MessageBuilder &operator=(const MessageBuilder &);
  flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline flatbuffers::Offset<Message> CreateMessage(
    flatbuffers::FlatBufferBuilder &_fbb,
    const IA20::Net::Conn::Engine::FB::Header *header = 0,
    IA20::Net::Conn::Engine::FB::Action action_type = IA20::Net::Conn::Engine::FB::Action_NONE,
    flatbuffers::Offset<void> action = 0) {
  MessageBuilder builder_(_fbb);
  builder_.add_action(action);
  builder_.add_header(header);
  builder_.add_action_type(action_type);
  return builder_.Finish();
}

flatbuffers::Offset<Message> CreateMessage(flatbuffers::FlatBufferBuilder &_fbb, const MessageT *_o, const flatbuffers::rehasher_function_t *_rehasher = nullptr);

inline VoteRequestT *VoteRequest::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<IA20::Net::Conn::Engine::FB::VoteRequestT> _o = std::unique_ptr<IA20::Net::Conn::Engine::FB::VoteRequestT>(new VoteRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void VoteRequest::UnPackTo(VoteRequestT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = term(); _o->term = _e; }
  { auto _e = candidate(); _o->candidate = _e; }
  { auto _e = lastLogEntry(); if (_e) _o->lastLogEntry = std::unique_ptr<IA20::Net::Conn::Engine::FB::LogEntryId>(new IA20::Net::Conn::Engine::FB::LogEntryId(*_e)); }
}

inline flatbuffers::Offset<VoteRequest> VoteRequest::Pack(flatbuffers::FlatBufferBuilder &_fbb, const VoteRequestT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVoteRequest(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<VoteRequest> CreateVoteRequest(flatbuffers::FlatBufferBuilder &_fbb, const VoteRequestT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const VoteRequestT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _term = _o->term;
  auto _candidate = _o->candidate;
  auto _lastLogEntry = _o->lastLogEntry ? _o->lastLogEntry.get() : 0;
  return IA20::Net::Conn::Engine::FB::CreateVoteRequest(
      _fbb,
      _term,
      _candidate,
      _lastLogEntry);
}

inline VoteResponseT *VoteResponse::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<IA20::Net::Conn::Engine::FB::VoteResponseT> _o = std::unique_ptr<IA20::Net::Conn::Engine::FB::VoteResponseT>(new VoteResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void VoteResponse::UnPackTo(VoteResponseT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = term(); _o->term = _e; }
  { auto _e = candidate(); _o->candidate = _e; }
  { auto _e = granted(); _o->granted = _e; }
}

inline flatbuffers::Offset<VoteResponse> VoteResponse::Pack(flatbuffers::FlatBufferBuilder &_fbb, const VoteResponseT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateVoteResponse(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<VoteResponse> CreateVoteResponse(flatbuffers::FlatBufferBuilder &_fbb, const VoteResponseT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const VoteResponseT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _term = _o->term;
  auto _candidate = _o->candidate;
  auto _granted = _o->granted;
  return IA20::Net::Conn::Engine::FB::CreateVoteResponse(
      _fbb,
      _term,
      _candidate,
      _granted);
}

inline AppendLogRequestT *AppendLogRequest::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<IA20::Net::Conn::Engine::FB::AppendLogRequestT> _o = std::unique_ptr<IA20::Net::Conn::Engine::FB::AppendLogRequestT>(new AppendLogRequestT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AppendLogRequest::UnPackTo(AppendLogRequestT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = matchLogEntry(); if (_e) _o->matchLogEntry = std::unique_ptr<IA20::Net::Conn::Engine::FB::LogEntryId>(new IA20::Net::Conn::Engine::FB::LogEntryId(*_e)); }
  { auto _e = dataLogEntry(); if (_e) _o->dataLogEntry = std::unique_ptr<IA20::Net::Conn::Engine::FB::LogEntryId>(new IA20::Net::Conn::Engine::FB::LogEntryId(*_e)); }
  { auto _e = leaderCommitIndex(); _o->leaderCommitIndex = _e; }
  { auto _e = data(); if (_e) { _o->data.resize(_e->size()); for (flatbuffers::uoffset_t _i = 0; _i < _e->size(); _i++) { _o->data[_i] = _e->Get(_i); } } }
}

inline flatbuffers::Offset<AppendLogRequest> AppendLogRequest::Pack(flatbuffers::FlatBufferBuilder &_fbb, const AppendLogRequestT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateAppendLogRequest(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<AppendLogRequest> CreateAppendLogRequest(flatbuffers::FlatBufferBuilder &_fbb, const AppendLogRequestT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const AppendLogRequestT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _matchLogEntry = _o->matchLogEntry ? _o->matchLogEntry.get() : 0;
  auto _dataLogEntry = _o->dataLogEntry ? _o->dataLogEntry.get() : 0;
  auto _leaderCommitIndex = _o->leaderCommitIndex;
  auto _data = _o->data.size() ? _fbb.CreateVector(_o->data) : 0;
  return IA20::Net::Conn::Engine::FB::CreateAppendLogRequest(
      _fbb,
      _matchLogEntry,
      _dataLogEntry,
      _leaderCommitIndex,
      _data);
}

inline AppendLogResponseT *AppendLogResponse::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<IA20::Net::Conn::Engine::FB::AppendLogResponseT> _o = std::unique_ptr<IA20::Net::Conn::Engine::FB::AppendLogResponseT>(new AppendLogResponseT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void AppendLogResponse::UnPackTo(AppendLogResponseT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = dataLogEntry(); if (_e) _o->dataLogEntry = std::unique_ptr<IA20::Net::Conn::Engine::FB::LogEntryId>(new IA20::Net::Conn::Engine::FB::LogEntryId(*_e)); }
  { auto _e = success(); _o->success = _e; }
}

inline flatbuffers::Offset<AppendLogResponse> AppendLogResponse::Pack(flatbuffers::FlatBufferBuilder &_fbb, const AppendLogResponseT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateAppendLogResponse(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<AppendLogResponse> CreateAppendLogResponse(flatbuffers::FlatBufferBuilder &_fbb, const AppendLogResponseT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const AppendLogResponseT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _dataLogEntry = _o->dataLogEntry ? _o->dataLogEntry.get() : 0;
  auto _success = _o->success;
  return IA20::Net::Conn::Engine::FB::CreateAppendLogResponse(
      _fbb,
      _dataLogEntry,
      _success);
}

inline MessageT *Message::UnPack(const flatbuffers::resolver_function_t *_resolver) const {
  std::unique_ptr<IA20::Net::Conn::Engine::FB::MessageT> _o = std::unique_ptr<IA20::Net::Conn::Engine::FB::MessageT>(new MessageT());
  UnPackTo(_o.get(), _resolver);
  return _o.release();
}

inline void Message::UnPackTo(MessageT *_o, const flatbuffers::resolver_function_t *_resolver) const {
  (void)_o;
  (void)_resolver;
  { auto _e = header(); if (_e) _o->header = std::unique_ptr<IA20::Net::Conn::Engine::FB::Header>(new IA20::Net::Conn::Engine::FB::Header(*_e)); }
  { auto _e = action_type(); _o->action.type = _e; }
  { auto _e = action(); if (_e) _o->action.value = IA20::Net::Conn::Engine::FB::ActionUnion::UnPack(_e, action_type(), _resolver); }
}

inline flatbuffers::Offset<Message> Message::Pack(flatbuffers::FlatBufferBuilder &_fbb, const MessageT* _o, const flatbuffers::rehasher_function_t *_rehasher) {
  return CreateMessage(_fbb, _o, _rehasher);
}

inline flatbuffers::Offset<Message> CreateMessage(flatbuffers::FlatBufferBuilder &_fbb, const MessageT *_o, const flatbuffers::rehasher_function_t *_rehasher) {
  (void)_rehasher;
  (void)_o;
  struct _VectorArgs { flatbuffers::FlatBufferBuilder *__fbb; const MessageT* __o; const flatbuffers::rehasher_function_t *__rehasher; } _va = { &_fbb, _o, _rehasher}; (void)_va;
  auto _header = _o->header ? _o->header.get() : 0;
  auto _action_type = _o->action.type;
  auto _action = _o->action.Pack(_fbb);
  return IA20::Net::Conn::Engine::FB::CreateMessage(
      _fbb,
      _header,
      _action_type,
      _action);
}

inline bool VerifyAction(flatbuffers::Verifier &verifier, const void *obj, Action type) {
  switch (type) {
    case Action_NONE: {
      return true;
    }
    case Action_VoteRequest: {
      auto ptr = reinterpret_cast<const IA20::Net::Conn::Engine::FB::VoteRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Action_VoteResponse: {
      auto ptr = reinterpret_cast<const IA20::Net::Conn::Engine::FB::VoteResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Action_AppendLogRequest: {
      auto ptr = reinterpret_cast<const IA20::Net::Conn::Engine::FB::AppendLogRequest *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Action_AppendLogResponse: {
      auto ptr = reinterpret_cast<const IA20::Net::Conn::Engine::FB::AppendLogResponse *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyActionVector(flatbuffers::Verifier &verifier, const flatbuffers::Vector<flatbuffers::Offset<void>> *values, const flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyAction(
        verifier,  values->Get(i), types->GetEnum<Action>(i))) {
      return false;
    }
  }
  return true;
}

inline void *ActionUnion::UnPack(const void *obj, Action type, const flatbuffers::resolver_function_t *resolver) {
  switch (type) {
    case Action_VoteRequest: {
      auto ptr = reinterpret_cast<const IA20::Net::Conn::Engine::FB::VoteRequest *>(obj);
      return ptr->UnPack(resolver);
    }
    case Action_VoteResponse: {
      auto ptr = reinterpret_cast<const IA20::Net::Conn::Engine::FB::VoteResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    case Action_AppendLogRequest: {
      auto ptr = reinterpret_cast<const IA20::Net::Conn::Engine::FB::AppendLogRequest *>(obj);
      return ptr->UnPack(resolver);
    }
    case Action_AppendLogResponse: {
      auto ptr = reinterpret_cast<const IA20::Net::Conn::Engine::FB::AppendLogResponse *>(obj);
      return ptr->UnPack(resolver);
    }
    default: return nullptr;
  }
}

inline flatbuffers::Offset<void> ActionUnion::Pack(flatbuffers::FlatBufferBuilder &_fbb, const flatbuffers::rehasher_function_t *_rehasher) const {
  switch (type) {
    case Action_VoteRequest: {
      auto ptr = reinterpret_cast<const IA20::Net::Conn::Engine::FB::VoteRequestT *>(value);
      return CreateVoteRequest(_fbb, ptr, _rehasher).Union();
    }
    case Action_VoteResponse: {
      auto ptr = reinterpret_cast<const IA20::Net::Conn::Engine::FB::VoteResponseT *>(value);
      return CreateVoteResponse(_fbb, ptr, _rehasher).Union();
    }
    case Action_AppendLogRequest: {
      auto ptr = reinterpret_cast<const IA20::Net::Conn::Engine::FB::AppendLogRequestT *>(value);
      return CreateAppendLogRequest(_fbb, ptr, _rehasher).Union();
    }
    case Action_AppendLogResponse: {
      auto ptr = reinterpret_cast<const IA20::Net::Conn::Engine::FB::AppendLogResponseT *>(value);
      return CreateAppendLogResponse(_fbb, ptr, _rehasher).Union();
    }
    default: return 0;
  }
}

inline ActionUnion::ActionUnion(const ActionUnion &u) : type(u.type), value(nullptr) {
  switch (type) {
    case Action_VoteRequest: {
      FLATBUFFERS_ASSERT(false);  // IA20::Net::Conn::Engine::FB::VoteRequestT not copyable.
      break;
    }
    case Action_VoteResponse: {
      value = new IA20::Net::Conn::Engine::FB::VoteResponseT(*reinterpret_cast<IA20::Net::Conn::Engine::FB::VoteResponseT *>(u.value));
      break;
    }
    case Action_AppendLogRequest: {
      FLATBUFFERS_ASSERT(false);  // IA20::Net::Conn::Engine::FB::AppendLogRequestT not copyable.
      break;
    }
    case Action_AppendLogResponse: {
      FLATBUFFERS_ASSERT(false);  // IA20::Net::Conn::Engine::FB::AppendLogResponseT not copyable.
      break;
    }
    default:
      break;
  }
}

inline void ActionUnion::Reset() {
  switch (type) {
    case Action_VoteRequest: {
      auto ptr = reinterpret_cast<IA20::Net::Conn::Engine::FB::VoteRequestT *>(value);
      delete ptr;
      break;
    }
    case Action_VoteResponse: {
      auto ptr = reinterpret_cast<IA20::Net::Conn::Engine::FB::VoteResponseT *>(value);
      delete ptr;
      break;
    }
    case Action_AppendLogRequest: {
      auto ptr = reinterpret_cast<IA20::Net::Conn::Engine::FB::AppendLogRequestT *>(value);
      delete ptr;
      break;
    }
    case Action_AppendLogResponse: {
      auto ptr = reinterpret_cast<IA20::Net::Conn::Engine::FB::AppendLogResponseT *>(value);
      delete ptr;
      break;
    }
    default: break;
  }
  value = nullptr;
  type = Action_NONE;
}

inline const flatbuffers::TypeTable *ActionTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, -1 },
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_SEQUENCE, 0, 1 },
    { flatbuffers::ET_SEQUENCE, 0, 2 },
    { flatbuffers::ET_SEQUENCE, 0, 3 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    IA20::Net::Conn::Engine::FB::VoteRequestTypeTable,
    IA20::Net::Conn::Engine::FB::VoteResponseTypeTable,
    IA20::Net::Conn::Engine::FB::AppendLogRequestTypeTable,
    IA20::Net::Conn::Engine::FB::AppendLogResponseTypeTable
  };
  static const char * const names[] = {
    "NONE",
    "VoteRequest",
    "VoteResponse",
    "AppendLogRequest",
    "AppendLogResponse"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_UNION, 5, type_codes, type_refs, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *HeaderTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_USHORT, 0, -1 },
    { flatbuffers::ET_USHORT, 0, -1 }
  };
  static const int64_t values[] = { 0, 2, 4 };
  static const char * const names[] = {
    "dstServerId",
    "srcServerId"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 2, type_codes, nullptr, values, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *LogEntryIdTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_USHORT, 0, -1 },
    { flatbuffers::ET_UINT, 0, -1 }
  };
  static const int64_t values[] = { 0, 4, 8 };
  static const char * const names[] = {
    "term",
    "index"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_STRUCT, 2, type_codes, nullptr, values, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *VoteRequestTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_USHORT, 0, -1 },
    { flatbuffers::ET_USHORT, 0, -1 },
    { flatbuffers::ET_SEQUENCE, 0, 0 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    IA20::Net::Conn::Engine::FB::LogEntryIdTypeTable
  };
  static const char * const names[] = {
    "term",
    "candidate",
    "lastLogEntry"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 3, type_codes, type_refs, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *VoteResponseTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_USHORT, 0, -1 },
    { flatbuffers::ET_USHORT, 0, -1 },
    { flatbuffers::ET_BOOL, 0, -1 }
  };
  static const char * const names[] = {
    "term",
    "candidate",
    "granted"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 3, type_codes, nullptr, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *AppendLogRequestTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_UINT, 0, -1 },
    { flatbuffers::ET_UCHAR, 1, -1 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    IA20::Net::Conn::Engine::FB::LogEntryIdTypeTable
  };
  static const char * const names[] = {
    "matchLogEntry",
    "dataLogEntry",
    "leaderCommitIndex",
    "data"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 4, type_codes, type_refs, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *AppendLogResponseTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_BOOL, 0, -1 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    IA20::Net::Conn::Engine::FB::LogEntryIdTypeTable
  };
  static const char * const names[] = {
    "dataLogEntry",
    "success"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 2, type_codes, type_refs, nullptr, names
  };
  return &tt;
}

inline const flatbuffers::TypeTable *MessageTypeTable() {
  static const flatbuffers::TypeCode type_codes[] = {
    { flatbuffers::ET_SEQUENCE, 0, 0 },
    { flatbuffers::ET_UTYPE, 0, 1 },
    { flatbuffers::ET_SEQUENCE, 0, 1 }
  };
  static const flatbuffers::TypeFunction type_refs[] = {
    IA20::Net::Conn::Engine::FB::HeaderTypeTable,
    IA20::Net::Conn::Engine::FB::ActionTypeTable
  };
  static const char * const names[] = {
    "header",
    "action_type",
    "action"
  };
  static const flatbuffers::TypeTable tt = {
    flatbuffers::ST_TABLE, 3, type_codes, type_refs, nullptr, names
  };
  return &tt;
}

inline const IA20::Net::Conn::Engine::FB::Message *GetMessage(const void *buf) {
  return flatbuffers::GetRoot<IA20::Net::Conn::Engine::FB::Message>(buf);
}

inline const IA20::Net::Conn::Engine::FB::Message *GetSizePrefixedMessage(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<IA20::Net::Conn::Engine::FB::Message>(buf);
}

inline Message *GetMutableMessage(void *buf) {
  return flatbuffers::GetMutableRoot<Message>(buf);
}

inline bool VerifyMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<IA20::Net::Conn::Engine::FB::Message>(nullptr);
}

inline bool VerifySizePrefixedMessageBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<IA20::Net::Conn::Engine::FB::Message>(nullptr);
}

inline void FinishMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<IA20::Net::Conn::Engine::FB::Message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<IA20::Net::Conn::Engine::FB::Message> root) {
  fbb.FinishSizePrefixed(root);
}

inline std::unique_ptr<IA20::Net::Conn::Engine::FB::MessageT> UnPackMessage(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<IA20::Net::Conn::Engine::FB::MessageT>(GetMessage(buf)->UnPack(res));
}

inline std::unique_ptr<IA20::Net::Conn::Engine::FB::MessageT> UnPackSizePrefixedMessage(
    const void *buf,
    const flatbuffers::resolver_function_t *res = nullptr) {
  return std::unique_ptr<IA20::Net::Conn::Engine::FB::MessageT>(GetSizePrefixedMessage(buf)->UnPack(res));
}

}  // namespace FB
}  // namespace Engine
}  // namespace Conn
}  // namespace Net
}  // namespace IA20

#endif  // FLATBUFFERS_GENERATED_RPC_IA20_NET_CONN_ENGINE_FB_H_
