#Thu Dec  9 02:16:11 PM CET 2021
FILES+=ia20/dm/ComplexDataObject
FILES+=ia20/dm/ComplexType
FILES+=ia20/dm/DataObject
FILES+=ia20/dm/exception/ConversionException
FILES+=ia20/dm/exception/Exception
FILES+=ia20/dm/IntegerDataObject
FILES+=ia20/dm/IntegerType
FILES+=ia20/dm/memory/MemoryManager
FILES+=ia20/dm/proxy/Converter
FILES+=ia20/dm/SimpleDataObject
FILES+=ia20/dm/SimpleType
FILES+=ia20/dm/StringDataObject
FILES+=ia20/dm/StringType
FILES+=ia20/dm/Type
FILES+=ia20/dm/TypedValue
